### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by joelczk** [projectdiscovery/asnmap#174] opened 2023-09-05 17:46 UTC
It seems like asnmap is is facing some bugs due to the asnmap version check api being down. I am currently using the latest version of asnmap, but it seems that we the https://api.pdtm.sh/api/v1/tools/asnmap?arch=amd64&go_version=go1.20.4&os=linux&v=v1.0.4 cannot be reached
![image](https://github.com/projectdiscovery/asnmap/assets/42378287/5b755044-3b95-4c55-b464-3ac3bc6b8c27)

**Comment by bill-e-ghote** [comment] 2023-09-06 00:19
I'm seeing:
[FTL] invalid character '<' looking for beginng of value

on every lookup (IP address, domain name) immediately after I did a 'go install' from latest.
-version: v1.0.4

Is this related, maybe?

**Comment by joelczk** [comment] 2023-09-06 02:22
I am seeing that as well when I re-run asnmap again
<img width="834" alt="image" src="https://github.com/projectdiscovery/asnmap/assets/42378287/d95ee158-d4a5-4c8d-ba10-8b8e94af0f6d">

**Comment by dogancanbakir** [comment] 2023-09-07 08:43
@joelczk,
You were getting an error due to some issues with our backend services. We made some updates, and it should be fixed now.

@bill-e-ghote ,
Can you create a separate issue for the error you're getting? Thanks!

Feel free to reopen if the error persists or if you have any questions!

**Closed by dogancanbakir** 2023-09-07 08:43 UTC

**Comment by bill-e-ghote** [comment] 2023-09-08 23:43
I tried it again just now in the same terminal window without updating the software and it works as expected. Sorry, I can't reproduce the issue, but whatever changed appears to have resolved it. Thanks.

**Comment by NoPurposeInLife** [comment] 2023-10-11 04:56
Unfortunately, I'm still facing the same error as @joelczk, using the latest version v1.0.5, thanks!

![image](https://github.com/projectdiscovery/asnmap/assets/30126475/503ef7bc-31a1-47ac-ac8a-c9454d8e2556)

**Comment by dogancanbakir** [comment] 2023-10-13 12:29
bill-e-ghote,
@joelczk,
@NoPurposeInLife,
Tracked at https://github.com/projectdiscovery/asnmap/issues/198
