### ISSUE TITLE
[FTL] invalid character '<' looking for beginning of value - version v1.0.5 

### ISSUE THREAD

**Issue by amit-sec** [projectdiscovery/asnmap#198] opened 2023-10-13 06:44 UTC
asnmap -v

   ___   _____  __
  / _ | / __/ |/ /_ _  ___ ____
 / __ |_\ \/    /  ' \/ _  / _ \
/_/ |_/___/_/|_/_/_/_/\_,_/ .__/
                         /_/

                projectdiscovery.io

[INF] Current asnmap version v1.0.5 (latest)
[FTL] invalid cha
<img width="798" alt="Asnmap" src="https://github.com/projectdiscovery/asnmap/assets/66508064/21c9dc9b-bdd0-4cb5-b4c2-d46faebcbf53">
racter '<' looking for beginning of value

**Comment by iamahmedtahar** [comment] 2023-10-13 09:55
same thing with me

**Comment by ehsandeep** [comment] 2023-10-13 13:40
@dogancanbakir It's an issue with API, which is getting down randomly because of high load - https://status.projectdiscovery.io/

<img width="907" alt="image" src="https://github.com/projectdiscovery/asnmap/assets/8293321/99d1a4e5-cb01-4c8a-b1f1-fde516fdaac3">

**Comment by joelczk** [comment] 2023-10-15 05:06
@dogancanbakir and @ehsandeep, I am experiencing the same issue today as well. Is that due to the high load of the asnmap api today as well?
<img width="854" alt="image" src="https://github.com/projectdiscovery/asnmap/assets/42378287/c765942e-02c7-4573-a02f-92c75791e193">

**Comment by iamahmedtahar** [comment] 2023-10-15 13:19
> @dogancanbakir and @ehsandeep, I am experiencing the same issue today as well. Is that due to the high load of the asnmap api today as well? <img alt="image" width="854" src="https://user-images.githubusercontent.com/42378287/275303318-c765942e-02c7-4573-a02f-92c75791e193.png">

You right

**Comment by dogancanbakir** [comment] 2023-10-16 10:19
Thank you for your patience. We are working on this internally and will follow up with you as soon as possible.

**Comment by imbas007** [comment] 2023-10-26 12:49
invalid character '<' looking for beginning of value

![image](https://github.com/projectdiscovery/asnmap/assets/100182585/3c75e269-d8d0-4ce5-8b2b-1370047061e3)

**Comment by Mzack9999** [comment] 2023-10-26 13:13
The API daemon outage is under investigation and hopefully will be fixed with a better lock-free implementation - Tracked at https://github.com/projectdiscovery/asnmap-server/issues/21

**Comment by AnImpulsiveHuman** [comment] 2023-10-27 02:48
Hello Team,

I'm not sure if this might help you but here it is anyway.

I don't think that the **invalid character '<' looking for beginning of value** error doesn't randomly happen, at least in my case.

For me, it happens specifically with certain ASNs, AS15169 in my case.

I'm giving two screenshots to show when it worked and when it didn't. 

**Screenshot of running asnmap on AS14421 where it worked as intended**
<img width="493" alt="1" src="https://github.com/projectdiscovery/asnmap/assets/64655668/bf4c3f7c-e11c-45e6-823b-eae38e1baa24">


**Screenshot of running asnmap on AS15169 where the error appears**
<img width="541" alt="2" src="https://github.com/projectdiscovery/asnmap/assets/64655668/2b87967d-f54d-4e29-9515-0129b5e9bd6c">


These screenshots were taken simultaneously. This, along with the fact that it always happens for a specific ASN, it gives me a feeling that the error might not be because of the API going down randomly because of high load.

**Comment by apsry** [comment] 2023-10-30 03:24
![image](https://github.com/projectdiscovery/asnmap/assets/55017061/c67aa0ca-0ca6-46cd-9d5b-ee25b972f45d)

**Comment by ui0x** [comment] 2023-11-05 00:17
Any update here? Would really love to be able to use the repo. Thank you!

**Comment by ehsandeep** [comment] 2023-11-05 11:19
Hello everyone!

We found an issue with the API server due to high traffic. We're improving it to handle high usage and will deploy a fix soon. We'll update once it's done.

**Comment by ehsandeep** [comment] 2023-11-09 14:09
should be fixed by now with latest release!

**Closed by ehsandeep** 2023-11-09 14:09 UTC
Labels: Status: Completed, Type: Bug
